### ISSUE TITLE
How to remove ?

### ISSUE THREAD

**Issue by sureshCPE** [megahertz/jquery.get-word-by-event#1]
How to remove the added event for the tag 

E.g $('p').getWordByEvent('click', function(e, word) {
    alert('You have clicked "' + word + '" word')
});

how to remove the click event for the tag <p>

**Comment by megahertz** [comment]
Now you can remove all handlers for specified event: $('p').off('click'); But I will add a possibility to remove event listener by the plugin as soon as possible.

**Comment by megahertz** [comment]
Done. Now you can use $('p').getWordByEvent('click', false); to remove handler

**Comment by sureshCPE** [comment]
Thank U
